// AngularApp/src/app/components/sign-in/sign-in.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import {
  FormBuilder,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { CommonModule } from '@angular/common';
import { ButtonComponent } from "../shared/button/button.component";

@Component({
  selector: 'app-sign-in',
  templateUrl: './sign-in.component.html',
  styleUrls: ['./sign-in.component.scss'],
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, ButtonComponent],
})
export class SigninComponent implements OnInit {
  signinForm!: FormGroup;
  isButtonActive: boolean = false;

  @Output() formSubmitted: EventEmitter<{
    username: string;
    password: string;
  }> = new EventEmitter();

  constructor(private fb: FormBuilder) {}

  ngOnInit(): void {
    this.signinForm = this.fb.group({
      username: ['', [Validators.required, Validators.minLength(5)]],
      password: ['', [Validators.required, Validators.minLength(5)]],
    });

    this.signinForm.valueChanges.subscribe(() => {
      this.checkButtonActive();
    });
  }

  checkButtonActive(): void {
    this.isButtonActive = this.signinForm.valid;
  }

  submitForm(): void {
    if (this.signinForm.invalid) {
      return;
    }

    const { username, password } = this.signinForm.value;
    this.formSubmitted.emit({ username, password });
  }
}

<div class="col-lg-5 col-md-8 col-10 rounded p-3 bg-light mx-auto mt-3">
  <form [formGroup]="signinForm">
    <h3 class="text-success"><b>Sign-In</b></h3>

    <div class="form-group mt-2">
      <label for="username">Username</label>
      <input
        id="username"
        type="text"
        class="form-control"
        placeholder="Min 5 characters"
        formControlName="username"
      />
      <div
        *ngIf="
          signinForm.get('username')?.invalid &&
          signinForm.get('username')?.touched
        "
        class="text-danger"
      >
        Username is required and must be at least 5 characters long.
      </div>
    </div>

    <div class="form-group mt-2">
      <label for="password">Password</label>
      <input
        id="password"
        type="password"
        class="form-control"
        placeholder="Min 5 characters"
        formControlName="password"
      />
      <div
        *ngIf="
          signinForm.get('password')?.invalid &&
          signinForm.get('password')?.touched
        "
        class="text-danger"
      >
        Password is required and must be at least 5 characters long.
      </div>
    </div>

    <div class="form-group mt-2">
      <button
        type="button"
        class="btn btn-success"
        [disabled]="!isButtonActive"
        (click)="submitForm()"
      >
        Sign in
      </button>
    </div>
  </form>

  <div class="card mt-4">
    <div class="card-body">
      If you do not have your credentials, please ask the supervisor.
      <div class="text-secondary">Available in the README.md file</div>
    </div>
  </div>
</div>

// ReactApp/src/components/Signin.tsx
import { useEffect, useState } from "react";
import Button from "./Button";
import TextForm from "./TextForm";
import { useNavigate } from "react-router-dom";
import config from "./../config.json";
import { useDispatch } from "react-redux";
import { updatedUsername } from "./redux/slices/user-slice";
import { AlertManager } from "../managers/AlertManager";
import { ApiRequestHandler } from "../http/ApiRequestHandler";

export default function Signin() {
  const [username, setUsername] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const [isButtonActive, setIsButtonActive] = useState<boolean>(false);
  const navigate = useNavigate();
  const dispatch = useDispatch();

  const apiRequestHandler = ApiRequestHandler.getInstance();
  const alertManager = new AlertManager();

  useEffect(() => {
    if (username.length >= 5 && password.length >= 5) {
      setIsButtonActive(true);
    } else {
      setIsButtonActive(false);
    }
  }, [username, password]);

  const handleButtonClick = () => {
    const logInAsync = async () => {
      const tokenObj: any = await apiRequestHandler.logIn(username, password);

      if (typeof tokenObj.token !== "string") {
        alertManager.displayAlert("Could not log in, check your username or password", "danger");
        return;
      }

      dispatch(updatedUsername(username));
      navigate(`${config.locationsViewClientEndpoint}`);
    };

    logInAsync();
  };

  return (
    <div className="col-lg-5 col-md-8 col-10 rounded p-3 bg-light mx-auto mt-3 ">
      <div className="form-inline mt-3">
        <h3 className="text-success">
          <b>Sign-In</b>
        </h3>
        <div className="form-group mt-2">
          <label>Username</label>
          <TextForm
            placeholderValue="Min 5 characters"
            inputType="text"
            onChange={(value) => setUsername(value)}
          />
        </div>
        <div className="form-group mt-2">
          <label>Password</label>
          <TextForm
            placeholderValue={"Min 5 characters"}
            inputType="password"
            onChange={(value) => setPassword(value)}
          />
        </div>
        <div className="form-group mt-2">
          <Button
            text="Sign in"
            active={isButtonActive}
            spacing={0}
            type="success"
            onClick={handleButtonClick}
          />
        </div>
      </div>
      <div className="card mt-4">
        <div className="card-body">
          {"If you do not have your credentials, please ask the supervisor"}
          <div className="text-secondary">{"Available in the README.md file :)"}</div>
        </div>
      </div>
    </div>
  );
}
