// AngularApp/src/app/components/desk-list/desk-list.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import { Desk } from '../../models/Desk';
import { User } from '../../models/User';
import { CommonModule } from '@angular/common';
import { RangeComponent } from '../shared/range/range.component';
import { ButtonComponent } from '../shared/button/button.component';

@Component({
  selector: 'app-desk-list',
  templateUrl: './desk-list.component.html',
  styleUrls: ['./desk-list.component.scss'],
  standalone: true,
  imports: [CommonModule, RangeComponent, ButtonComponent],
})
export class DeskListComponent implements OnInit {
  @Input() desks: Desk[] = [];
  @Input() user: User | null = null;

  @Output() onBookClick = new EventEmitter<string>();
  @Output() onUnbookClick = new EventEmitter<string>();
  @Output() onRemoveClick = new EventEmitter<string>();
  @Output() onEnableClick = new EventEmitter<string>();
  @Output() onDisableClick = new EventEmitter<string>();
  @Output() onRangeChange = new EventEmitter<number>();

  hoveredIndex: number | null = null;
  isHoverSupported: boolean = false;

  ngOnInit(): void {
    const mediaQuery = window.matchMedia('(hover: hover)');
    this.isHoverSupported = mediaQuery.matches;

    mediaQuery.addEventListener('change', (event) => {
      this.isHoverSupported = event.matches;
    });
  }

  handleMouseEnter(index: number): void {
    this.hoveredIndex = index;
  }

  handleMouseLeave(): void {
    this.hoveredIndex = null;
  }
}

<ul class="list-group mt-3">
  <li
    *ngFor="let desk of desks; let index = index"
    [ngClass]="{
      'bg-white': desk.username === null && desk.isEnabled,
      'bg-light': desk.username !== null || !desk.isEnabled
    }"
    class="list-group-item"
    (mouseenter)="handleMouseEnter(index)"
    (mouseleave)="handleMouseLeave()"
  >
    <div>
      <b>{{ desk.deskName }}</b>
    </div>

    <div
      [ngClass]="{
        'text-success': desk.username === null && desk.isEnabled,
        'text-danger': desk.username !== null || !desk.isEnabled
      }"
      class="d-flex"
    >
      <ng-container *ngIf="desk.username === null && desk.isEnabled">
        Available
      </ng-container>
      <ng-container *ngIf="desk.username === null && !desk.isEnabled">
        Disabled
      </ng-container>
      <ng-container *ngIf="desk.username !== null">
        <span class="d-lg-none d-md-none d-sm-block d-xs-block">
          Booked from <b>{{ desk.startTime }}</b> <br />
          until the end of <b>{{ desk.endTime }}</b>
        </span>
        <span class="d-lg-block d-md-block d-none">
          Booked from <b>{{ desk.startTime }}</b> until the end of
          <b>{{ desk.endTime }}</b>
        </span>
      </ng-container>
    </div>

    <div class="text-primary mb-2">
      <ng-container *ngIf="user?.username === desk.username">
        Your booking
      </ng-container>
      <ng-container
        *ngIf="
          user?.isAdmin &&
          desk.username !== user?.username &&
          desk.username !== null
        "
      >
        Booked by {{ desk.username }}
      </ng-container>
    </div>

    <div class="d-flex">
      <app-button
        *ngIf="user?.username === desk.username"
        [text]="'Unbook desk'"
        [active]="true"
        [type]="'primary'"
        (onClick)="onUnbookClick.emit(desk.deskName)"
      ></app-button>

      <app-button
        *ngIf="
          desk.username === null && desk.isEnabled && user?.bookedDesk === null
        "
        [text]="'Book desk'"
        [active]="true"
        [type]="'primary'"
        (onClick)="onBookClick.emit(desk.deskName)"
      ></app-button>

      <app-button
        *ngIf="user?.isAdmin && desk.isEnabled && desk.username === null"
        [text]="'Disable'"
        [active]="true"
        [type]="'secondary'"
        [spacing]="2"
        (onClick)="onDisableClick.emit(desk.deskName)"
      ></app-button>

      <app-button
        *ngIf="user?.isAdmin && !desk.isEnabled && desk.username === null"
        [text]="'Enable'"
        [active]="true"
        [type]="'secondary'"
        [spacing]="0"
        (onClick)="onEnableClick.emit(desk.deskName)"
      ></app-button>

      <app-button
        *ngIf="user?.isAdmin && desk.username === null"
        [text]="'Remove'"
        [active]="true"
        [type]="'danger'"
        [spacing]="desk.isEnabled ? 0 : 2"
        (onClick)="onRemoveClick.emit(desk.deskName)"
      ></app-button>
    </div>

    <div
      class="mt-4 mb-1"
      *ngIf="
        desk.username === null &&
        desk.isEnabled &&
        (isHoverSupported
          ? hoveredIndex === index && user?.bookedDesk === null
          : user?.bookedDesk === null)
      "
    >
      <app-range
        [title]="'Book ' + desk.deskName + ' for'"
        [suffix]="'day(s)'"
        [minValue]="1"
        [maxValue]="7"
        [step]="1"
        [defaultValue]="1"
        (valueChange)="onRangeChange.emit($event)"
      ></app-range>
    </div>
  </li>

  <h5 *ngIf="desks.length === 0" class="text-danger">Nothing to display</h5>
</ul>

// client-app/src/components/DeskList.tsx
import { useEffect, useState } from 'react';
import { Desk } from '../types/Desk'
import Button from './Button'
import Range from './Range'
import { useAppSelector } from './redux/hooks';

interface DeskListProps {
  desks: Desk[],
  onBookClick: (deskName: string) => void,
  onUnbookClick: (deskName: string) => void,
  onRemoveClick: (deskName: string) => void,
  onEnableClick: (deskName: string) => void,
  onDisableClick: (deskName: string) => void,
  onRangeChange: (value: number) => void
}

export default function DeskList({desks, onBookClick, onUnbookClick, onRemoveClick, onEnableClick, onDisableClick, onRangeChange}: DeskListProps) {
  const [hoveredIndex, setHoveredIndex] = useState<number | null>(null);
  const [isHoverSupported, setIsHoverSupported] = useState(false);
  const user = useAppSelector((state) => state.user);

  useEffect(() => {
    const mediaQuery = window.matchMedia('(hover: hover)');
    
    const handleHoverChange = (event: any) => {
      setIsHoverSupported(event.matches);
    };

    mediaQuery.addEventListener('change', handleHoverChange);
    setIsHoverSupported(mediaQuery.matches);

    return () => {
      mediaQuery.removeEventListener('change', handleHoverChange);
    };
  }, []);

  return (
    <>
      <ul className="list-group mt-3">
        {
          desks.length !== 0 ? (
            desks.map((desk: Desk, index) =>
            <li 
              key={index}
              className={
                `list-group-item 
                ${desk.username === null && desk.isEnabled ? "bg-white" : "bg-light"}`
              }
              onMouseEnter={() => setHoveredIndex(index)}
              onMouseLeave={() => setHoveredIndex(null)}
            >
              <div>
                <b>{`${desk.deskName}`}</b>
              </div>
              <div className={`d-flex ${desk.username === null && desk.isEnabled ? "text-success" : "text-danger"}`}>
                {
                  (desk.username === null && desk.isEnabled) && <>{"Available"}</>
                }
                {
                  (desk.username === null && !desk.isEnabled) && <>{"Disabled"}</>
                }
                {
                  (desk.username !== null) && 
                  <>
                    <span className='d-lg-none d-md-none d-sm-block d-xs-block'>{"Booked from\u00A0"} <b>{desk.startTime}</b> <br/>{"until the end of\u00A0"} <b>{desk.endTime}</b></span>
                    <span className='d-lg-block d-md-block d-none'>{"Booked from\u00A0"} <b>{desk.startTime}</b> {"\u00A0until the end of\u00A0"} <b>{desk.endTime}</b></span>
                  </>
                }
              </div>
                <div className="text-primary mb-2">
                  {
                    (desk.username === user.username) && "Your booking"
                  }
                  {
                    (user.isAdmin && desk.username !== null && desk.username !== user.username) && `Booked by ${desk.username}`
                  }
                </div>
                <div className="d-flex">
                  {
                    (desk.username === user.username) ?
                    <Button
                      text="Unbook desk"
                      active={desk.username === user.username}
                      spacing={0}
                      type="primary"
                      onClick={() => onUnbookClick(desk.deskName)}
                    />
                    :
                    <Button
                      text="Book desk"
                      active={desk.username === null && desk.isEnabled}
                      spacing={0}
                      type="primary"
                      onClick={() => onBookClick(desk.deskName)}
                    />
                  }
                                    {
                    (user.isAdmin && desk.isEnabled) &&
                    <Button
                      text="Disable"
                      active={desk.username === null}
                      spacing={2}
                      type="secondary"
                      onClick={() => onDisableClick(desk.deskName)}
                    />
                  }
                  {
                    (user.isAdmin && !desk.isEnabled) &&
                    <Button
                      text="Enable"
                      active={desk.username === null}
                      spacing={2}
                      type="secondary"
                      onClick={() => onEnableClick(desk.deskName)}
                    />
                  }
                  {
                    (user.isAdmin) &&
                    <Button
                      text="Remove"
                      active={desk.username === null}
                      spacing={0}
                      type="danger"
                      onClick={() => onRemoveClick(desk.deskName)}
                    />
                  }
                </div>
              { 
                (desk.username === null && desk.isEnabled &&
                  (isHoverSupported ? (hoveredIndex === index && user.bookedDesk === null) : user.bookedDesk === null)) && (
                  <div className={`mt-4 mb-1"}`}>
                    <Range
                      title={`Book ${desk.deskName} for`}
                      suffix={"day(s)"}
                      minValue={1}
                      maxValue={7}
                      step={1}
                      defaultValue={1}
                      onChange={onRangeChange}
                    />
                  </div>
                )
              }
            </li>
          )) 
          : <h5 className="text-danger">{"Nothing to display :("}</h5>
        }
      </ul>
    </>
  )
}
