// AngularApp/src/app/components/top-bar/top-bar.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { UserService } from '../../services/user.service';
import { Observable } from 'rxjs';
import { CommonModule } from '@angular/common';
import { User } from '../../models/User';
import { TokenService } from '../../services/token.service';

@Component({
  selector: 'app-top-bar',
  templateUrl: './top-bar.component.html',
  styleUrls: ['./top-bar.component.scss'],
  standalone: true,
  imports: [CommonModule],
})
export class TopBarComponent {
  user$: Observable<User | null>;

  constructor(
    private router: Router,
    protected userService: UserService,
    private tokenService: TokenService
  ) {
    this.user$ = this.userService.user$;
  }

  handleButtonClick() {
    this.userService.clearUser();
    this.tokenService.clearToken();
    this.router.navigate(['/']);
  }
}

<div class="container">
  <div class="row">
    <div class="col-12 col-md-3"></div>
    <div class="col-12 col-md-6">
      <h3 class="text-center mt-3">
        <b class="text-primary">Hot Desk Booking System</b>
      </h3>
    </div>
    <div class="col-12 col-md-3 mt-3 justify-content-md-end">
      <div
        *ngIf="user$ | async as user"
        class="d-flex justify-content-center justify-content-md-end"
      >
        <span class="text-secondary align-content-center me-3">
          {{ user.isAdmin ? "Administrator" : "Employee" }}:
          <b>{{ user.username }}</b>
        </span>
        <button
          *ngIf="userService.getUser()"
          class="btn btn-danger"
          (click)="handleButtonClick()"
        >
          Sign out
        </button>
      </div>
    </div>
  </div>

  <div
    *ngIf="user$ | async as user"
    class="mb-3 d-flex justify-content-center align-items-center user-details-container"
  >
    <div *ngIf="user.bookedDesk">
      <span class="text-primary">Current booking:</span>
      <span class="text-primary">
        {{ user.bookedDesk.deskName }} in {{ user.bookedDeskLocation }} until
        {{ user.bookedDesk.endTime }}
      </span>
    </div>
  </div>
</div>

// client-app/src/components/TopBar.tsx
import useLocalStorageState from "use-local-storage-state";
import Button from "./Button";
import { useNavigate } from "react-router-dom";
import config from "./../config.json";
import { useAppSelector } from "./redux/hooks";
import Alert from "./Alert";
import { useEffect } from "react";
import { useDispatch } from "react-redux";
import {
  updatedBookedDesk,
  updatedBookedDeskLocation,
  updatedIsAdmin,
  updatedUsername,
} from "./redux/slices/user-slice";
import { UserInfoOutput } from "../http/ApiInterfaces";
import { ApiRequestHandler } from "../http/ApiRequestHandler";

interface TopBarProps {
  isUserInfoVisible: boolean;
}

export default function TopBar({ isUserInfoVisible }: TopBarProps) {
  const [token] = useLocalStorageState("token", { defaultValue: "" });
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const user = useAppSelector((state) => state.user);

  const apiRequestHandler = ApiRequestHandler.getInstance();

  useEffect(() => {
    if (!isUserInfoVisible && user.username === "User") {
      return;
    }

    const getUserInfo = async () => {
      const userInfo: UserInfoOutput = await apiRequestHandler.getUserInfo(
        token
      );

      if (!userInfo) {
        dispatch(updatedUsername("User"));
        return;
      }

      dispatch(updatedIsAdmin(userInfo.isAdmin));
      dispatch(updatedUsername(userInfo.username));

      if (userInfo.bookedDesk) {
        dispatch(updatedBookedDesk(userInfo.bookedDesk));
        dispatch(updatedBookedDeskLocation(userInfo.bookedDeskLocation));
      }
    };

    getUserInfo();
  }, []);

  const handleButtonClick = () => {
    apiRequestHandler.logOut(token);

    dispatch(updatedUsername("User"));
    dispatch(updatedIsAdmin(false));
    dispatch(updatedBookedDesk(null));
    dispatch(updatedBookedDeskLocation(null));

    navigate(config.mainViewClientEndpoint);
  };

  return (
    <div>
      <div className="row mb-3">
        <div className="col-12 col-md-3"></div>
        <div className="col-12 col-md-6">
          <h3 className="text-center mt-3">
            <b className="text-primary">Hot Desk Booking System</b>
          </h3>
          <Alert />
        </div>
        <div className="col-12 col-md-3 mt-3 justify-content-md-end">
          <div className="d-flex justify-content-center justify-content-md-end">
            {isUserInfoVisible && (
              <Button
                text={"Sign out"}
                active={true}
                spacing={0}
                type="danger"
                onClick={handleButtonClick}
              />
            )}
          </div>
        </div>
      </div>
      {isUserInfoVisible && (
        <div className="mb-3">
          <h5 className="text-secondary">
            {`${user.isAdmin ? "Administrator" : "Employee"}:`}{" "}
            <b className="text-secondary">{user.username}</b>
          </h5>
          {user.bookedDesk && (
            <h6>
              <span className="d-block text-primary mb-1">
                {"Current booking"}
              </span>
              <span className="d-block text-primary">
                {`${user.bookedDesk.deskName} in ${user.bookedDeskLocation} until ${user.bookedDesk.endTime}`}
              </span>
            </h6>
          )}
        </div>
      )}
    </div>
  );
}
