// client-app/src/views/LocationsView.tsx
import { Location } from '../types/Location'
import LocationList from '../components/LocationList';
import Button from '../components/Button';
import config from './../config.json';
import { useNavigate } from 'react-router-dom';
import { useEffect, useState } from 'react';
import Popup from '../components/Popup';
import ApiRequestHandler from '../http/ApiRequestHandler';
import useLocalStorageState from 'use-local-storage-state';
import TopBar from '../components/TopBar';
import { useAppSelector } from '../components/redux/hooks';
import { AlertManager } from '../managers/AlertManager';

export default function LocationsView() {
  const [locations, setLocations] = useState<Location[]>([]);
  const [isAddLocationPopupVisible, setIsLocationPopupVisible] = useState<boolean>(false);
  const [isLocationListVisible, setIsLocationListVisible] = useState<boolean>(false);
  const [token] = useLocalStorageState("token", { defaultValue: ""});
  const navigate = useNavigate();
  const user = useAppSelector((state) => state.user);

  const apiRequestHandler: ApiRequestHandler = new ApiRequestHandler();
  const alertManager: AlertManager = new AlertManager();

  // eslint-disable-next-line
  useEffect(() => {
    const fetchLocationsAsync = async () => {
      const fetchedLocations = await apiRequestHandler.getAllLocationNames();
      
      if (!Array.isArray(fetchedLocations)) {
        alertManager.displayAlert("Could not load locations", "danger");
        setLocations([]);
        return;
      }

      setLocations(fetchedLocations);

      setTimeout(() => {
        setIsLocationListVisible(true);
      }, 250);
    }
    
    fetchLocationsAsync();
  }, []);

  const handleAddButtonClick = () => {
    setIsLocationPopupVisible(true);
  }

  const handleChooseLocationButtonClick = (locationName: string) => {
    navigate(`${config.desksViewClientEndpoint}`, { state: { locationName: locationName } });
  }

  const handleRemoveButtonClick = async (locationName: string) => {
    try {
      const removeLocationStatusCode = await apiRequestHandler.removeLocation(token, locationName);

      if (removeLocationStatusCode !== 200) {
        alertManager.displayAlert(`Could not remove the location ${locationName}`, "danger");
        return;
      }

      const updatedLocations = locations.filter(location => location.locationName !== locationName);
      setLocations(updatedLocations);
  
    } catch (error) {
      alertManager.displayAlert("Unexpected error", "danger");
    }
  }

  const handlePopupSubmit = async (locationName: string) => {
    try {
      const addLocationStatusCode = await apiRequestHandler.addLocation(token, locationName);
      setIsLocationPopupVisible(false);

      if (addLocationStatusCode !== 201) {
        alertManager.displayAlert(`Could not add the location: ${locationName}`, "danger");
        return;
      }

      const newLocation: Location = {
        locationName: locationName,
        totalDeskCount: 0,
        availableDeskCount: 0
      };

      setLocations([...locations, newLocation]);
    } catch (error) {
      alertManager.displayAlert(`Unexpected error`, "danger");
    }
  }

  return (
    <div className="container col-lg-6 col-md-8 col-12 mb-5">
      <TopBar isUserInfoVisible={true} />
      <h4>Locations</h4>
      <Popup 
        title={"Name a new location"}
        inputFormPlaceholderText={"Insert the name here"}
        visible={isAddLocationPopupVisible}
        onSubmit={handlePopupSubmit}
        onClose={() => setIsLocationPopupVisible(false)}
      />
      {
        isLocationListVisible ?
        <>
        {
          user.isAdmin &&
          <>
            <Button
              text={"Add location"}
              active={true}
              spacing={0}
              type={"success"}
              onClick={handleAddButtonClick}
            />
          </>
        }
          <LocationList 
            locations={locations}
            onChooseClick={handleChooseLocationButtonClick}
            onRemoveClick={handleRemoveButtonClick}
          />
        </>
         :
        <h5 className="mt-3 text-success">Loading data...</h5>
      }
    </div>
  )
}

// AngularApp/src/app/views/locations-view/locations-view.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { MatDialog } from '@angular/material/dialog';
import { ApiService } from '../../services/api.service';
import { PopupComponent } from '../../components/popup/popup.component';
import { Location } from '../../models/Location';
import { LocationListComponent } from '../../components/location-list/location-list.component';
import { CommonModule } from '@angular/common';
import { Observable } from 'rxjs';
import { User } from '../../models/User';
import { UserService } from '../../services/user.service';
import { ButtonComponent } from '../../components/shared/button/button.component';

@Component({
  selector: 'app-locations-view',
  templateUrl: './locations-view.component.html',
  styleUrl: './locations-view.component.scss',
  standalone: true,
  imports: [CommonModule, LocationListComponent, ButtonComponent],
})
export class LocationsViewComponent implements OnInit {
  locations: Location[] = [];
  isAddLocationPopupVisible = false;
  isLocationListVisible = false;
  user$: Observable<User | null>;

  constructor(
    private apiService: ApiService,
    private router: Router,
    private dialog: MatDialog,
    private userService: UserService,
    private route: ActivatedRoute
  ) {
    this.user$ = userService.user$;
  }

  ngOnInit(): void {
    const resolvedLocations = this.route.snapshot.data['locations'];
    this.locations = resolvedLocations.map((location: Location) => ({
      locationName: location.locationName,
      totalDeskCount: location.totalDeskCount,
      availableDeskCount: location.availableDeskCount,
    }));

    setTimeout(() => {
      this.isLocationListVisible = true;
    }, 250);
  }

  handleAddButtonClick(): void {
    const dialogRef = this.dialog.open(PopupComponent, {
      data: {
        title: 'Name a new location',
        inputFormPlaceholderText: 'Insert the name here',
      },
    });

    dialogRef.afterClosed().subscribe((result: string) => {
      if (result) {
        this.handlePopupSubmit(result);
      }
    });
  }

  handleChooseLocationButtonClick(locationName: string): void {
    this.router.navigate([`/locations/${locationName}/desks`]);
  }

  handleRemoveButtonClick(locationName: string): void {
    this.apiService.removeLocation(locationName).subscribe(
      (statusCode: number) => {
        if (statusCode === 200) {
          this.locations = this.locations.filter(
            (location) => location.locationName !== locationName
          );
        } else {
          console.error(`Could not remove the location ${locationName}`);
        }
      },
      (error: any) => {
        console.error('Unexpected error', error);
      }
    );
  }

  handlePopupSubmit(locationName: string): void {
    this.apiService.addLocation(locationName).subscribe(
      (statusCode: number) => {
        if (statusCode === 201) {
          const newLocation: Location = {
            locationName,
            totalDeskCount: 0,
            availableDeskCount: 0,
          };
          this.locations = [...this.locations, newLocation];
        } else {
          console.error(`Could not add the location: ${locationName}`);
        }
      },
      (error: any) => {
        console.error('Unexpected error', error);
      }
    );
  }
}

<div class="container col-lg-6 col-md-8 col-12 mb-5">
  <h5>Locations</h5>

  <ng-container *ngIf="isLocationListVisible; else loading">
    <app-button
      *ngIf="(user$ | async)?.isAdmin"
      [text]="'Add location'"
      [active]="true"
      [type]="'success'"
      (onClick)="handleAddButtonClick()"
    ></app-button>

    <app-location-list
      [locations]="locations"
      (onChooseClick)="handleChooseLocationButtonClick($event)"
      (onRemoveClick)="handleRemoveButtonClick($event)"
    >
    </app-location-list>
  </ng-container>

  <ng-template #loading>
    <h5 class="mt-3 text-success">Loading data...</h5>
  </ng-template>
</div>
