// client-app/src/views/DesksView.tsx
import DeskList from "../components/DeskList";
import Button from "../components/Button";
import { useEffect, useState } from "react";
import { Desk } from "../types/Desk";
import Popup from "../components/Popup";
import { useLocation, useNavigate } from "react-router-dom";
import config from "./../config.json";
import TopBar from "../components/TopBar";
import useLocalStorageState from "use-local-storage-state";
import { useAppSelector } from "../components/redux/hooks";
import { AlertManager } from "../managers/AlertManager";
import { useDispatch } from "react-redux";
import {
  updatedBookedDesk,
  updatedBookedDeskLocation,
} from "../components/redux/slices/user-slice";
import ApiRequestHandler from "../http/ApiRequestHandler";

export default function DesksView() {
  const [desks, setDesks] = useState<Desk[]>([]);
  const [isPopupVisible, setIsPopupVisible] = useState<boolean>(false);
  const [isDeskListVisible, setIsDeskListVisible] = useState<boolean>(false);
  const [bookingDays, setBookingDays] = useState<number>(1);
  const [token] = useLocalStorageState("token", { defaultValue: "" });
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const location = useLocation();
  const { locationName } = location.state ?? "-";
  const isUserAdmin = useAppSelector((state) => state.user.isAdmin);

  const apiRequestHandler = ApiRequestHandler.getInstance();
  const alertManager: AlertManager = new AlertManager();

  // eslint-disable-next-line
  useEffect(() => {
    if (locationName === undefined) {
      navigate(config.locationsViewClientEndpoint);
    }

    const fetchDesksAsync = async () => {
      const fetchedDesks: Desk[] = await apiRequestHandler.getDesks(
        token,
        locationName
      );

      if (!Array.isArray(fetchedDesks)) {
        alertManager.displayAlert("Could not load desks", "danger");
        navigate(config.locationsViewClientEndpoint);
        return;
      }

      setDesks(fetchedDesks);

      setTimeout(() => {
        setIsDeskListVisible(true);
      }, 250);
    };

    fetchDesksAsync();
  }, []);

  const handleAddButtonClick = () => {
    setIsPopupVisible(true);
  };

  const handleBookButtonClick = async (deskName: string) => {
    const bookedDesk: Desk = await apiRequestHandler.bookDesk(
      token,
      deskName,
      locationName,
      bookingDays
    );

    if (bookedDesk.deskName === undefined || !bookedDesk) {
      alertManager.displayAlert(
        `Could not book the desk: ${deskName}`,
        "danger"
      );
      return;
    }

    const deskIndex = desks.findIndex((desk) => desk.deskName === deskName);

    const updatedDesks = [...desks];
    updatedDesks[deskIndex] = bookedDesk;

    dispatch(updatedBookedDesk(bookedDesk));
    dispatch(updatedBookedDeskLocation(locationName));
    setDesks(updatedDesks);
  };

  const handleUnbookButtonClick = async (deskName: string) => {
    const unbookedDesk: Desk = await apiRequestHandler.unbookDesk(
      token,
      deskName,
      locationName
    );

    if (unbookedDesk.deskName === undefined || !unbookedDesk) {
      alertManager.displayAlert(
        `Could not unbook the desk: ${deskName}`,
        "danger"
      );
      return;
    }

    const deskIndex = desks.findIndex((desk) => desk.deskName === deskName);

    const updatedDesks = [...desks];
    updatedDesks[deskIndex] = unbookedDesk;

    dispatch(updatedBookedDesk(null));
    dispatch(updatedBookedDeskLocation(locationName));
    setDesks(updatedDesks);
  };

  const handleRemoveButtonClick = async (deskName: string) => {
    try {
      const removeDeskStatusCode = await apiRequestHandler.removeDesk(
        token,
        deskName,
        locationName
      );

      if (removeDeskStatusCode !== 200) {
        alertManager.displayAlert(
          `Could not remove the desk: ${deskName}`,
          "danger"
        );
        return;
      }

      const updatedDesks = desks.filter((desk) => desk.deskName !== deskName);
      setDesks(updatedDesks);
    } catch (error) {
      alertManager.displayAlert(`Unexpected error`, "danger");
    }
  };

  const handleEnableButtonClick = async (deskName: string) => {
    try {
      const returnedDesk: Desk = await apiRequestHandler.setDeskAvailability(
        token,
        deskName,
        locationName,
        true
      );

      if (returnedDesk.deskName === undefined || !returnedDesk) {
        alertManager.displayAlert(
          `Could not enable the desk: ${deskName}`,
          "danger"
        );
        return;
      }

      const deskIndex = desks.findIndex((desk) => desk.deskName === deskName);

      const updatedDesks = [...desks];
      updatedDesks[deskIndex] = returnedDesk;
      setDesks(updatedDesks);
    } catch (error) {
      alertManager.displayAlert(`Unexpected error`, "danger");
    }
  };

  const handleDisableButtonClick = async (deskName: string) => {
    try {
      const returnedDesk: Desk = await apiRequestHandler.setDeskAvailability(
        token,
        deskName,
        locationName,
        false
      );

      if (returnedDesk.deskName === undefined || !returnedDesk) {
        alertManager.displayAlert(
          `Could not disable the desk: ${deskName}`,
          "danger"
        );
        return;
      }

      const deskIndex = desks.findIndex((desk) => desk.deskName === deskName);

      const updatedDesks = [...desks];
      updatedDesks[deskIndex] = returnedDesk;
      setDesks(updatedDesks);
    } catch (error) {
      alertManager.displayAlert(`Unexpected error`, "danger");
    }
  };

  const handlePopupSubmit = async (deskName: string) => {
    try {
      const addDeskStatusCode = await apiRequestHandler.addDesk(
        token,
        deskName,
        locationName
      );
      setIsPopupVisible(false);

      if (addDeskStatusCode !== 201) {
        alertManager.displayAlert(
          `Could not add the desk: ${deskName}`,
          "danger"
        );
        return;
      }

      const newDesk: Desk = {
        deskName: deskName,
        isEnabled: true,
        username: null,
        startTime: null,
        endTime: null,
      };

      setDesks([...desks, newDesk]);
    } catch (error) {
      alertManager.displayAlert(`Unexpected error`, "danger");
    }
  };

  const handleDaysRangeChange = (value: number) => {
    setBookingDays(value);
  };

  const handleGoBackButtonClick = () => {
    navigate(`${config.locationsViewClientEndpoint}`);
  };

  return (
    <div className="container col-lg-6 col-md-10 col-12 mb-5">
      <TopBar isUserInfoVisible={true} />
      <h4>
        {"Desks in location: "}
        <b>{`${locationName}`}</b>
      </h4>
      <Popup
        title={"Name a new desk"}
        inputFormPlaceholderText={"Insert the name here"}
        visible={isPopupVisible}
        onSubmit={handlePopupSubmit}
        onClose={() => setIsPopupVisible(false)}
      />
      {isDeskListVisible ? (
        <>
          {isUserAdmin && (
            <Button
              text={"Add desk"}
              active={true}
              spacing={0}
              type={"success"}
              onClick={handleAddButtonClick}
            />
          )}
          <Button
            text={"Return to locations"}
            active={true}
            spacing={1}
            type={"secondary"}
            onClick={handleGoBackButtonClick}
          />
          <DeskList
            desks={desks}
            onBookClick={handleBookButtonClick}
            onUnbookClick={handleUnbookButtonClick}
            onRemoveClick={handleRemoveButtonClick}
            onEnableClick={handleEnableButtonClick}
            onDisableClick={handleDisableButtonClick}
            onRangeChange={handleDaysRangeChange}
          />
        </>
      ) : (
        <h5 className="mt-3 text-success">Loading data...</h5>
      )}
    </div>
  );
}

// AngularApp/src/app/views/desks-view/desks-view.component.ts
import { Component, OnInit } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { ActivatedRoute, Router } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { Desk } from '../../models/Desk';
import { PopupComponent } from '../../components/popup/popup.component';
import { CommonModule } from '@angular/common';
import { DeskListComponent } from '../../components/desk-list/desk-list.component';
import { UserService } from '../../services/user.service';
import { Observable } from 'rxjs';
import { User } from '../../models/User';
import { ButtonComponent } from '../../components/shared/button/button.component';

@Component({
  selector: 'app-desks-view',
  templateUrl: './desks-view.component.html',
  styleUrls: ['./desks-view.component.scss'],
  standalone: true,
  imports: [CommonModule, DeskListComponent, ButtonComponent],
})
export class DesksViewComponent implements OnInit {
  desks: Desk[] = [];
  isPopupVisible: boolean = false;
  isDeskListVisible: boolean = false;
  bookingDays: number = 1;
  locationName: string = '-';
  user$: Observable<User | null>;

  constructor(
    private apiService: ApiService,
    private router: Router,
    private route: ActivatedRoute,
    private dialog: MatDialog,
    private userService: UserService
  ) {
    this.user$ = userService.user$;
  }

  ngOnInit(): void {
    this.locationName = this.route.snapshot.paramMap.get('locationName') ?? '-';
    this.desks = this.route.snapshot.data['desks'];

    setTimeout(() => {
      this.isDeskListVisible = true;
    }, 250);
  }

  handleAddButtonClick(): void {
    const dialogRef = this.dialog.open(PopupComponent, {
      data: {
        title: 'Name a new desk',
        inputFormPlaceholderText: 'Insert the name here',
      },
    });

    dialogRef.componentInstance.formSubmitted.subscribe((deskName: string) => {
      this.handlePopupSubmit(deskName); // Handle popup submission
    });
  }

  handlePopupSubmit(deskName: string): void {
    this.apiService.addDesk(deskName, this.locationName).subscribe(() => {
      const newDesk: Desk = {
        deskName,
        isEnabled: true,
        username: null,
        startTime: null,
        endTime: null,
      };
      this.desks.push(newDesk);
    });
  }

  handleBookButtonClick(deskName: string): void {
    this.apiService
      .bookDesk(deskName, this.locationName, this.bookingDays)
      .subscribe((bookedDesk: Desk) => {
        this.updateDeskState(deskName, bookedDesk);
        const user = this.userService.getUser();
        if (user) {
          const updatedUser = {
            ...user,
            bookedDesk: bookedDesk,
            bookedDeskLocation: this.locationName,
          };
          this.userService.updateUser(updatedUser);
        }
      });
  }

  handleUnbookButtonClick(deskName: string): void {
    this.apiService
      .unbookDesk(deskName, this.locationName)
      .subscribe((unbookedDesk: Desk) => {
        this.updateDeskState(deskName, unbookedDesk);
        const user = this.userService.getUser();
        if (user) {
          const updatedUser = {
            ...user,
            bookedDesk: null,
            bookedDeskLocation: null,
          };
          this.userService.updateUser(updatedUser);
        }
      });
  }

  handleRemoveButtonClick(deskName: string): void {
    this.apiService.removeDesk(deskName, this.locationName).subscribe(() => {
      this.desks = this.desks.filter((desk) => desk.deskName !== deskName);
    });
  }

  handleEnableButtonClick(deskName: string): void {
    this.apiService
      .setDeskAvailability(deskName, this.locationName, true)
      .subscribe((enabledDesk: Desk) =>
        this.updateDeskState(deskName, enabledDesk)
      );
  }

  handleDisableButtonClick(deskName: string): void {
    this.apiService
      .setDeskAvailability(deskName, this.locationName, false)
      .subscribe((disabledDesk: Desk) =>
        this.updateDeskState(deskName, disabledDesk)
      );
  }

  handleDaysRangeChange(value: number): void {
    this.bookingDays = value;
  }

  handleGoBackButtonClick(): void {
    this.router.navigate(['/locations']);
  }

  private updateDeskState(deskName: string, updatedDesk: Desk): void {
    const deskIndex = this.desks.findIndex(
      (desk) => desk.deskName === deskName
    );

    this.desks[deskIndex] = updatedDesk;
  }
}

<div class="container col-lg-6 col-md-10 col-12 mb-5">
  <h5>
    Desks in location: <b>{{ locationName }}</b>
  </h5>

  <ng-container *ngIf="isDeskListVisible; else loading">
    <app-button
      *ngIf="(user$ | async)?.isAdmin"
      [text]="'Add desk'"
      [active]="true"
      [type]="'success'"
      (onClick)="handleAddButtonClick()"
    ></app-button>

    <app-button
      [text]="'Return to locations'"
      [active]="true"
      [type]="'secondary'"
      [spacing]="2"
      (onClick)="handleGoBackButtonClick()"
    ></app-button>

    <app-desk-list
      [desks]="desks"
      [user]="user$ | async"
      (onBookClick)="handleBookButtonClick($event)"
      (onUnbookClick)="handleUnbookButtonClick($event)"
      (onRemoveClick)="handleRemoveButtonClick($event)"
      (onEnableClick)="handleEnableButtonClick($event)"
      (onDisableClick)="handleDisableButtonClick($event)"
      (onRangeChange)="handleDaysRangeChange($event)"
    >
    </app-desk-list>
  </ng-container>

  <ng-template #loading>
    <h5 class="mt-3 text-success">Loading data...</h5>
  </ng-template>
</div>
