// client-app/src/components/LocationList.tsx
import { Location } from '../types/Location'
import Button from './Button'
import { useAppSelector } from './redux/hooks';

interface LocationListProps {
  locations: Location[],
  onChooseClick: (locationName: string) => void,
  onRemoveClick: (locationName: string) => void
}

export default function LocationList({locations, onChooseClick, onRemoveClick}: LocationListProps) {
  const isUserAdmin = useAppSelector((state) => state.user.isAdmin);
  
  return (
    <ul className="list-group mt-3">
      {
        locations.length !== 0 ? (
          locations.map((location: Location, index) =>
          <li
            key={index}
            className="list-group-item">
              <div><b>{`${location.locationName}`}</b></div>
              <div className="mb-2">{`Total desks: ${location.totalDeskCount}, available: ${location.availableDeskCount}`}</div>
              <Button
                text="Enter this location"
                active={true}
                spacing={0}
                type="primary"
                onClick={() => onChooseClick(location.locationName)}
              />
              {
                isUserAdmin &&
                  <Button
                  text="Remove"
                  active={location.totalDeskCount === 0}
                  spacing={3}
                  type="danger"
                  onClick={() => onRemoveClick(location.locationName)}
                />
              }
          </li>
        ))
        : <h5 className="text-danger">{"Nothing to display :("}</h5>
      }
    </ul>
  )
}

// AngularApp/src/app/components/location-list/location-list.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Location } from '../../models/Location';
import { CommonModule } from '@angular/common';
import { ButtonComponent } from '../shared/button/button.component';
import { User } from '../../models/User';

@Component({
  selector: 'app-location-list',
  templateUrl: './location-list.component.html',
  styleUrls: ['./location-list.component.scss'],
  standalone: true,
  imports: [CommonModule, ButtonComponent],
})
export class LocationListComponent {
  @Input() locations: Location[] = [];
  @Input() user: User | null = null;

  @Output() onChooseClick = new EventEmitter<string>();
  @Output() onRemoveClick = new EventEmitter<string>();

  handleChooseClick(locationName: string): void {
    this.onChooseClick.emit(locationName);
  }

  handleRemoveClick(locationName: string): void {
    this.onRemoveClick.emit(locationName);
  }
}

<ul class="list-group mt-3">
  <li
    *ngFor="let location of locations; let index = index"
    class="list-group-item"
  >
    <div>
      <b>{{ location.locationName }}</b>
    </div>
    <div class="mb-2">
      Total desks: {{ location.totalDeskCount }}, available:
      {{ location.availableDeskCount }}
    </div>

    <app-button
      [text]="'Enter location'"
      [active]="true"
      [type]="'primary'"
      (onClick)="handleChooseClick(location.locationName)"
    ></app-button>

    <app-button
      *ngIf="user?.isAdmin"
      [text]="'Remove'"
      [active]="(user?.isAdmin ?? false) && location.totalDeskCount === 0"
      [type]="'danger'"
      [spacing]="2"
      (onClick)="handleRemoveClick(location.locationName)"
    ></app-button>
  </li>

  <h5 class="text-danger" *ngIf="locations.length === 0">Nothing to display</h5>
</ul>
