// client-app/src/components/Range.tsx
import { useEffect, useState } from "react";

interface RangeProps {
  title: string;
  suffix: string;
  minValue: number;
  maxValue: number;
  step: number;
  defaultValue: number;
  onChange: (value: number) => void;
}

function Range({title, suffix, minValue, maxValue, step, defaultValue, onChange}: RangeProps) {
  const [value, setValue] = useState(defaultValue);

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setValue(parseInt(event.target.value));
  }

  useEffect(() => {
    onChange(value);
  }, [value]);
  
  return (
    <div className="d-flex align-items-center">
      <label className="form-label">{`${title}: ${value} ${suffix}`}</label>
      <div className="flex-grow-1">
        <input 
            className="form-range mx-2"
            type="range"
            value={value}
            min={minValue}
            max={maxValue}
            step={step}
            onChange={handleChange}
        />
      </div>
  </div>
  )
}

export default Range;

// AngularApp/src/app/components/shared/range/range.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';

@Component({
  selector: 'app-range',
  templateUrl: './range.component.html',
  styleUrls: ['./range.component.scss'],
  standalone: true,
  imports: [],
})
export class RangeComponent implements OnInit {
  @Input() title: string = '';
  @Input() suffix: string = '';
  @Input() minValue: number = 0;
  @Input() maxValue: number = 100;
  @Input() step: number = 1;
  @Input() defaultValue: number = 50;
  @Output() valueChange = new EventEmitter<number>();

  value: number = this.defaultValue;

  ngOnInit() {
    this.value = this.defaultValue;
  }

  onRangeChange(event: Event): void {
    const inputElement = event.target as HTMLInputElement;
    this.value = parseInt(inputElement.value);
    this.valueChange.emit(this.value);
  }
}

<div class="d-flex align-items-center">
  <label class="form-label">{{ title }}: {{ value }} {{ suffix }}</label>
  <div class="flex-grow-1">
    <input
      class="form-range mx-2"
      type="range"
      [value]="value"
      [min]="minValue"
      [max]="maxValue"
      [step]="step"
      (input)="onRangeChange($event)"
    />
  </div>
</div>
